data:
  train_csv: ../data/sample_train.csv
paths:
  model_out: ../models/rf_model.joblib
  preproc_out: ../models/preprocessor.joblib
  label_enc_out: ../models/label_encoder.joblib
model:
  rf_params:
    n_estimators: 100
    max_depth: 8
    random_state: 42
